### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [awvalenti/fugaescorregadia#80]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by awvalenti** [comment]
Hello! Sorry for the delay.

The project is kinda frozen, It will be resumed somewhen. But I'm actually
not accepting contributors for now.

I appreciate your interest in It! Just out of curiosity, how did you found
out about It?

André

Em qui., 29 de dez. de 2022 18:22, Code Hangen ***@***.***>
escreveu:

**Comment by ghost** [comment]
Hi awvalenti. 

> Hello! Sorry for the delay.
> The project is kinda frozen, It will be resumed somewhen. But I'm actually not accepting contributors for now.

thank you for feedback here.

> I appreciate your interest in It! Just out of curiosity, how did you found out about It?
> André
> Em qui., 29 de dez. de 2022 18:22, Code Hangen ***@***.***>
> escreveu:

So, I love games and open source projects, I've been researching a lot and I found this project searching on GitHub. I searched for old games and I really liked this game.
